# Generated by Django 5.2 on 2025-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=256)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('organizer', 'Organizer')], default='free', max_length=20)),
                ('language', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('admin_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('event_admin', 'Event Admin'), ('support_admin', 'Support Admin')], max_length=20, null=True)),
            ],
        ),
    ]
