# Generated by Django 5.2 on 2025-05-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', help_text='Source of the event (manual, ticketmaster, eventbrite, etc.)', max_length=50)),
                ('external_id', models.CharField(blank=True, help_text='External event ID from the source platform', max_length=128, null=True)),
                ('external_event_id', models.CharField(blank=True, help_text='External event ID for Ticketmaster, Eventbrite, etc.', max_length=128, null=True)),
                ('external_event_data', models.JSONField(blank=True, help_text='Raw event data for external events.', null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to='users.clerkuser')),
            ],
            options={
                'unique_together': {('user', 'event'), ('user', 'external_event_id')},
            },
        ),
    ]
