# Generated by Django 5.2 on 2025-05-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('user_signup', 'User Signup'), ('admin_change', 'Admin Change'), ('revenue_milestone', 'Revenue Milestone'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('event_create', 'Event Created'), ('event_update', 'Event Updated'), ('event_delete', 'Event Deleted')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.CharField(choices=[('all', 'All Admins'), ('super_admin', 'Super Admin Only')], default='all', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_notifications', to='users.clerkuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ticket_sales', models.BooleanField(default=True)),
                ('email_event_reminders', models.BooleanField(default=True)),
                ('email_new_features', models.BooleanField(default=True)),
                ('email_promotions', models.BooleanField(default=True)),
                ('push_ticket_sales', models.BooleanField(default=True)),
                ('push_event_reminders', models.BooleanField(default=True)),
                ('push_new_features', models.BooleanField(default=False)),
                ('push_new_events', models.BooleanField(default=True)),
                ('freq_realtime', models.BooleanField(default=True)),
                ('freq_daily', models.BooleanField(default=False)),
                ('freq_weekly', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='users.clerkuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('event_reminder', 'Event Reminder'), ('purchase_success', 'Purchase Success')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, help_text='Optional link related to the notification.', null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID (e.g., event ID, transaction ref)', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.clerkuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
