# Generated by Django 5.2 on 2025-05-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('event_reminder', 'Event Reminder'), ('purchase_success', 'Purchase Success'), ('new_ticket_sale', 'New Ticket Sale'), ('sales_milestone', 'Sales Milestone'), ('event_reminder_organizer', 'Event Reminder for Organizer')], max_length=50),
        ),
    ]
